### ISSUE TITLE
Error: Loading chunk 0 failed

### ISSUE THREAD

**Issue by joegaudet** [shipshapecode/ember-shepherd#639] opened 2020-12-03 01:16 UTC
When using the ember-sheppard tour addon, the first time I initialize the tour service in both dev or production it cannot find the chunk 0.

The path it seems to try and load is the following: 

http://localhost:4201/swiftfox/+/hotmailtreutel-denesik-and-jerde/admin/plan/calendar/2020/11/chunk.0.c68e453ef3dda7a025a1.js

When I reload the app, or re run the integration suite, the request is the more correct:

http://localhost:4201/swiftfox/assets/chunk.0.c68e453ef3dda7a025a1.js

I assume there's some esoteric webpack configuration I haven't figured out yet, any thoughts?

.joe

**Comment by GCheung55** [comment] 2020-12-03 02:02
@joegaudet If you have time, putting together a repo to reproduce the issue would be super helpful.

**Comment by rwwagner90** [comment] 2020-12-14 15:33
There have been some issues in the past with ember-auto-import. Let me release a new version of ember-shepherd and see if it helps any.

**Comment by rwwagner90** [comment] 2020-12-14 16:38
@joegaudet can you please try 11.0.2?

**Comment by joegaudet** [comment] 2020-12-15 17:48
I actually ended up solving the issue by configuring the publicAssertUrl
for auto import, seems to have cleared things up.

**Comment by rwwagner90** [comment] 2020-12-15 19:32
@joegaudet okay, but can you please try the latest version and see if it fixes the issue. I want to make sure this isn't a problem for anyone else!

**Comment by rwwagner90** [comment] 2021-04-18 00:59
Closing this for now, since there have been no updates.

**Closed by rwwagner90** 2021-04-18 00:59 UTC
