### ISSUE TITLE
Move disableScroll to Shepherd

### ISSUE THREAD

**Issue by rwwagner90** [shipshapecode/ember-shepherd#306] opened 2019-04-29 21:55 UTC

**Comment by st-h** [comment] 2019-06-21 10:26
@rwwagner90 did you already look into this or have any expectations on how this should be implemented? 
I am asking because I am unfortunately seeing the error message caused by bodyScrollLock on every redeployment in dev mode - and well... by now it's starting to annoy me, having to manually reload again after autoreload did its thing. So, I would like to look into resolving this somewhen in the near future.

**Comment by rwwagner90** [comment] 2019-06-21 11:45
@st-h what error?

**Comment by st-h** [comment] 2019-06-21 12:12
@rwwagner90 the one, we recently talked about: https://github.com/shipshapecode/ember-shepherd/issues/304#issuecomment-487503085

```
TypeError: window.addEventListener is not a function
    at Object.eval (webpack://__ember_auto_import__/./node_modules/body-scroll-lock/lib/bodyScrollLock.min.js?:4:405)
    at eval (webpack://__ember_auto_import__/./node_modules/body-scroll-lock/lib/bodyScrollLock.min.js?:3:37)
    at eval (webpack://__ember_auto_import__/./node_modules/body-scroll-lock/lib/bodyScrollLock.min.js?:4:118)
    at Object../node_modules/body-scroll-lock/lib/bodyScrollLock.min.js (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/vendor.js:124325:1)
    at __webpack_require__ (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/vendor.js:123929:30)
    at Module.eval [as callback] (webpack://__ember_auto_import__//private/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/cache-571-bundler/staging/app.js?:18:51)
    at Module.exports (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:104:1)
    at Module._reify (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:104:1)
    at requireModule (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:27:1)
    at Class._extractDefaultExport (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:422:1)
    at Class.resolveOther (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:103:1)
    at Class.resolve (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:163:1)
    at resolve (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container.js:1197:1)
    at Registry.resolve (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container.js:737:1)
    at Registry.resolve (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container.js:740:1)
    at factoryFor (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container.js:297:1)
    at instantiateFactory (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container.js:350:1)
    at lookup (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container.js:287:1)
    at Container.lookup (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container.js:131:1)
    at Class.lookup (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/runtime/lib/mixins/container_proxy.js:78:1)
    at Object.patchTourServiceNoop [as initialize] (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/stacktune/instance-initializers/tour.js:10:1)
    at /var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/engine/index.js:151:1
    at Vertices.each (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/dag-map.js:228:1)
    at Vertices.walk (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/dag-map.js:142:1)
    at DAG.each (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/dag-map.js:72:1)
    at DAG.topsort (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/dag-map.js:80:1)
    at Class._runInitializer (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/engine/index.js:166:1)
    at Class.runInstanceInitializers (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/engine/index.js:149:1)
    at Class._bootSync (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/application/instance.js:108:1)
    at /var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/engine/instance.js:84:1
    at initializePromise (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/rsvp.js:532:1)
    at new Promise (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/rsvp.js:1019:1)
    at Class.boot (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/engine/instance.js:84:1)
    at /Users/steve/code/stacktune/stacktune/node_modules/fastboot/src/ember-app.js:258:25
    at tryCatcher (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/rsvp.js:335:1)
    at invokeCallback (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/rsvp.js:506:1)
    at publish (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/rsvp.js:492:1)
    at /var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/ember-testing/lib/ext/rsvp.js:16:1
    at invokeWithOnError (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:344:1)
    at Queue.flush (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:226:1)
    at DeferredActionQueues.flush (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:423:1)
    at Backburner._end (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:957:1)
    at Backburner._boundAutorunEnd (/var/folders/yt/kw3pd9l52sd9bbpjrlpm47rm0000gn/T/broccoli-88836A6OacwE0N9en/out-573-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:626:1)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

should have added the trace here in first place. I thought I was able to work around that issue, however maybe I was wrong since it appeared again. I just wonder that no one else seems to be having issues with Fastboot when using ember-shepherd.

**Comment by rwwagner90** [comment] 2019-06-21 12:39
Ah okay. I forgot about that conversation. I can get `disableScroll` moved over soon.

**Comment by st-h** [comment] 2019-06-21 12:41
@rwwagner90 that would be awesome :) are you using fastboot together with shepherd? Just wondering if I am doing something wrong as nobody else seems to have run into that issue.

**Comment by rwwagner90** [comment] 2019-06-21 12:45
@st-h I actually don't have any projects using Shepherd or ember-shepherd currently. There will be a lot of a11y updates coming down from Shepherd this week too, so hopefully we can get a big release out fixing a lot of things 😃

**Comment by st-h** [comment] 2019-06-25 15:11
@rwwagner90 thanks a lot. Life is so much better without exceptions 😃 Noticed the buttons also have specific classes now, which makes styling & positioning a lot easier. Awesome 🎉 

I think we can also close this issue now

**Closed** 2019-06-25 17:12 UTC
Labels: enhancement
